#!/bin/csh

#foreach d (  03_malloc_use 04_malloc_a_few 05_malloc_a_lot 06_realloc_once 07_realloc_a_few 08_malloc_free 09_malloc_several_free 10_malloc_realloc 11_mallocs_reallocs 12_malloc_sizes 13_calloc_sizes 14_malloc_free_loop 15_malloc_really_big ) 
foreach d ( 12_calloc_once ) 
  mv $d/Makefile $d/Makefile.bak
  sed 's/02_malloc_nouse/'$d'/' 02_malloc_nouse/Makefile > $d/Makefile
  echo $d
end
